### ISSUE TITLE
Crashes when @doc is used without an argument.

### ISSUE THREAD

**Issue by kalouantonis** [kalouantonis/clojurebot#3]
When `@doc` is used with no parameters, clojurebot crashes and quits IRC.

```
2017-03-09 13:42:30	someuser	 @doc
2017-03-09 13:42:31	<--	lispbot (~lispbot@some-ip) has quit (Remote host closed the connection)
```

**Comment by emanuelmd** [comment]
I'm onto it

**Comment by emanuelmd** [comment]
#5

**Comment by kalouantonis** [comment]
Finally managed to get a stacktrace from a running instance.

```
:ragepandemic!~ragepande@SOME-IP PRIVMSG ##channel :@doc
Exception in thread "Thread-0" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at clojure.lang.Compiler.maybeResolveIn(Compiler.java:7184)
	at clojure.core$ns_resolve.invokeStatic(core.clj:4240)
	at clojure.core$ns_resolve.invokeStatic(core.clj:4229)
	at clojure.core$resolve.invokeStatic(core.clj:4242)
	at clojure.core$resolve.invoke(core.clj:4242)
	at clojurebot.core$fn__868.invokeStatic(core.clj:90)
	at clojurebot.core$fn__868.invoke(core.clj:87)
	at clojurebot.core$handle_message.invokeStatic(core.clj:47)
	at clojurebot.core$handle_message.invoke(core.clj:44)
	at clojurebot.irc$conn_handler.invokeStatic(irc.clj:49)
	at clojurebot.irc$conn_handler.invoke(irc.clj:39)
	at clojurebot.irc$connect$fn__837.invoke(irc.clj:60)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```
